//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public int id { get; set; }
        public string login { get; set; }
        public byte[] passwordHash { get;  set; }

        public string password { get { return BitConverter.ToString(passwordHash); } }

    }
}
